### ISSUE TITLE
Несколько замечаний и вопросов возникших в ходе проверки практики в CSC

### ISSUE THREAD

**Issue by MBkkt** [leoneed03/GDR#4]
1) Я бы написал какая версия видимо ubuntu? предполагается для сборки.
Так же хотелось бы видеть версию компилятора.

2) https://github.com/leoneed03/GDR/blob/dev/CMakeLists.txt#L271
 предлагается воспользоваться 
```
include(CTest)
if (BUILD_TESTING)
...
endif()
```
Опять таки флаги сборки выглядят стремно.

3) https://github.com/leoneed03/GDR/blob/dev/include/computationHandlers/RelativePosesComputationHandler.h#L38 кажется это бага и должен быть атомик

4) С точки зрения оценивания сложно понять что было сделано давно, а что сейчас, я ориентировался по пр. Но понятно что это такое себе, а учитывая их объем еще и совершенно неудобно

5) Отладочный вывод в консоль в коде библиотеки выглядит ужасно. Хотя вероятно совершенно неважно в рамках практики

6) Я видел много изменений с переформатированием, стоит добавить .clang-format.

7) CI не работает, это очень печально, хотя учитывая количество и обьем использованных библиотек я понимаю почему могут возникнуть сложности с его добавлением

Также я очень рекомендую такую практику как code review)

А в целом конечно производит впечатление что сделано довольно много.

**Comment by MBkkt** [comment]
Лол

**Comment by MBkkt** [comment]
А в чем смысл?

**Comment by leoneed03** [comment]
Прошу прощения за поздний ответ
Действительно, в README забыл указать в инструкциях строку, хотя она и была в travis.yml. Теперь добавил
git submodule update --init --recursive

Впрочем отмечу, что сборка CI в travis проходила

Добавил также версию убунту и компилятора

Остальные замечания считаю исправлять надобности нет

**Comment by MBkkt** [comment]
Очень странно, видимо я что-то перепутал с CI, почему то казалось что видел красный х на последнем коммите, извини за это замечание

**Comment by leoneed03** [comment]
Да, насчёт того, что было сделано:

Разработка ведётся с начала года, тогда же была начата осенняя практика. К сожалению за один семестр сделать все не получилось и практика перенеслась на следущий семестр. К началу семестра был разработан алгоритм и начата реализация (поиск и сопоставление ключевых точек и оценивание относительных поз)

В текущем семестре алгоритм был реализован полностью

**Comment by MBkkt** [comment]
Да я примерно так и понял. 
А по поводу пунктов 2,3,5,6 в issue, советую либо завести issue либо за repopen-ить это. Вообще закрывать issue просто так как-то не красиво было. 
Если что это все никак не влияет на мою оценку, просто несколько советов для улучшения этой кодовой базы, если ты конечно в этом заинтересован.

**Comment by leoneed03** [comment]
Да, спасибо
